### ISSUE TITLE
Documentation at radash-docs.vercel.app is not up to date

### ISSUE THREAD

**Issue by ristomatti** [rayepps/radash#130]
Docs seem to still be for v7.0.0. This might be the reason why #82 was reported even if already fixed.

![image](https://user-images.githubusercontent.com/9029939/198086849-fd2f228a-196b-4920-9960-cfdf3e390fd3.png)

**Comment by ZebZeb13** [comment]
Hello,
A big part of the documentation is not update online and on the repository Github

Is there a reason ? Do you need help ?

I really like radash but, I am a little bit faired when a beautiful documentation is not update

**Comment by rayepps** [comment]
I'm working on it. I'm trying to move the docs into the radash repository so management/updates are easier for contributors but its been time consuming. It's at the top of my list to get it updated but it also needs to be fixed in general, the separate repos thing with a huge nextjs app is not the great idea I thought it would be 😅

**Comment by ZebZeb13** [comment]
Ok, that's perfect !

**Comment by ristomatti** [comment]
Thank you!
