### ISSUE TITLE
Thoughts on adding `zip` methods?

### ISSUE THREAD

**Issue by Nickersoft** [rayepps/radash#154]
I recently found myself hand-rolling a `zipObject` method to avoid using Lodash, and even though it can be achieved via `reduce` I think adding some `zip` methods (such as `unzip`, `zipObject`, and `zip/unzipWith`) could offer a much more succinct interface:

```typescript
/**
 * Zips two arrays of even length together into an object
 *
 * @param keys The object's keys
 * @param values The object's values
 * @returns
 */
export function zipObject<Key extends string | number | symbol, Value>(keys: Key[], values: Value[]) {
  return keys.reduce((acc, key, idx) => ({ ...acc, [key]: values[idx] }), {} as Record<Key, Value>);
}
```

Happy to pick up the implementation, but wanted to make sure this stays in line with this project's philosophies.

Thoughts?

**Comment by rayepps** [comment]
Hi @Nickersoft 👋 thanks for brining this up! We currently have a [zip](https://radash-docs.vercel.app/docs/object-zip) but it combines two objects together, overriding attributes in the first with values in the second. Now that you bring this up I feel like I made a mistake in naming that zip 😬 this (what your proposing) is definitely the more standard use of the term zip.

We have a bunch of breaking changes queued up for a v10 release, we could rename the current zip to a more fitting name and add zip/unzip function. Or, we could find available names for the proposed zip/unzip functionality.

I'm leaning twoards option 2 for the sake of less breaking changes (with recognition I named things poorly) but I'm open to thoughts.

**Comment by rayepps** [comment]
*oh, forgot to say, yes! Big fan of zip/unzip functions! Just have to consider the names.

**Comment by Nickersoft** [comment]
Oh wow, thanks for the quick response!! I love how responsive you are and how supportive you are of all the issues here. Shows how much you really care ❤️ 

I'd actually opt for option 1, despite the unfortunate breaking change, mostly to avoid further confusion around this functionality. Technically speaking, the functionality Radash's current `zip` does is what `assign` does in Lodash (as well as `Object.assign()`). 

Zipping is generally understood to be emitting/producing tuples from two or more sources. In the Rx world, [`Observable.zip`](https://reactivex.io/documentation/operators/zip.html) accepts two observables and emits values from both observables as a tuple. Swift's [Combine framework does the same thing](https://developer.apple.com/documentation/combine/publisher/zip(_:_:)-8d7k7). 

For newcomers from Lodash, I feel like mixing around terms and ideologies can be confusing haha. I myself even had a bit of trouble adjusting to new function names like `sift` and `boil`, but definitely shifting around existing function names could just add to the confusion.

Sucks to be a breaking change, but at least it would just be renaming the existing `zip` to `assign` without breaking anything else.

**Comment by rayepps** [comment]
Thank you for the kind words!

I'm good with renaming the current zip. I agree it's probably better and more correct long term. It's not a big deal either, we'll do this work and bundle it in the v10 release and add it to the breaking changes list in the changelog. If anyone is using the current `zip` (I'm using it on 2 projects) it's an easy find/replace to update.

The functions not matching Lodash's function names is intentional because they don't _actually_ work the same in many cases I didn't want people to think they could directly swap lodash for radash. Radash is waaaay less dynamic than Lodash, that's the ethos, we value type safety and predictability over marginal convenience. In many cases the functions aren't going to work the same, so I intentionally named them differently.

Zip is a special case because it's so standard... rats.

I propose, this:
- rename the current `zip` to `mergo` (merge object) it sort of a natural sibling function to the current [merge](https://radash-docs.vercel.app/docs/array-merge) (open to other suggestions)
- implement `zip` and `unzip`

**Comment by Nickersoft** [comment]
Ah right, forgot there's an existing `merge` function 😅  I think `mergo` works for brevity, that or something like `mergeObject` – I'm also wondering if something like `assignDeep` might make sense, seeing that's _technically_ what it's doing (seeing it just overwrites keys, as opposed to merging array values, for example). Or just something that mentions `assign` in general – idk haha.

As far as the functions go – are we just doing `zip` and `unzip`? I my particular use case, I needed `zipObject` – to zip two arrays into an object. Lodash's `zip` just produces a 2D array of tuples. I'm happy to open some PRs – just want to clarify on what's being built lol.

**Comment by rayepps** [comment]
How about... `assign` haha I think that's perfect.

As far as what's being built, we're following your muse today Nick 😄 I like `zip` and `unzip` for arrays. I also like the zipping to an object. I do have a comment on the name, `zipObject` sounds like your doing a _zip_ operation on an _object_. How do you feel about `zipToObject`?

**Comment by Nickersoft** [comment]
Sorry for the delay @rayepps! Juggling quite a bit this week haha. I think `zipToObject` sounds perfect! I'll get a PR together 💪🏻
