### ISSUE TITLE
Make `min` function require a getter if the first argument is an array of objects

### ISSUE THREAD

**Issue by rayepps** [rayepps/radash#191]
The min function will accept an array of objects and no getter argument without error which is very error prone (I just found out the hard way).

### The Problem
```ts
import { min } from 'radash'

const books = [{ title: 'About Trains', published: 298448934 }, { title: 'About Trains: Revised', published: 2948445822 }]

const least = min(books)
```
This works but it shouldn't! Inside `min`, the two book objects are being compared (which will always result in false). What we expect is this
```ts
const least = min(books, b => b.published)
```

### The Solution

The `min` function should use better typing to insist that a second arg (the getter function) is required when the first argument is not an array of numbers.

I think this can be done using conditional types, I haven't dug into it yet but possibly something like:

```ts
const min = <
    TItem extends number | object, 
    TFunc extends TItem extends number ? undefined | (item: number) => number : (item: TItem) => number
> (
  array: readonly TItem[],
  getter?: TFunc
) => {
 // ...
} 
```

I'm not sure if this will work, just something to explore.

### AC

```ts
min([0, 1]) // ok
min([{ value: 0 }, { value: 1 }]) // type error
min([{ value: 0 }, { value: 1 }], x => x.value) // ok
```

**Comment by MarlonPassos-git** [comment]
the examples you showed are right, it shouldn't be an array of objects ?

```js
min([0, 1]) // ok
min([{ value: 0}, {value: 1 }]) // type error
min([{ value: 0}, {value: 1 }], x => x.value) // ok
```

**Comment by MarlonPassos-git** [comment]
@rayepps  I don't know if this is exactly what you wanted. I managed to implement something. Using functions because I found more than using "overload". But there must be some way to port this code to const

```ts
function min<T extends number>(array: readonly T[], getter?: undefined): T
function min<T extends object>(array: readonly T[], getter: (item: T) => number): T
function min<
  T extends number | object, 
  Func extends T extends object ? (item: T) => number : undefined
>(array: readonly T[], getter: Func ): T {
  const get = getter ? getter : (v: any) => v
  return boil(array, (a, b) => (get(a) < get(b) ? a : b))
}

min([0, 1]) // ok
min([{ value: 0 }, { value: 1 }]) // type error
min([{ value: "1" }, { value: "ss" }]) // type error
min([{ value: "a" }, { value: "a" }], x => x.value) // type error
min([{ value: 0, a: "a" }, { value: 1, a: "a" }], x => x.value) // ok
```

[view in typescript playgroud](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAWxmAPAFUQUwB5Q5gAmAzomCMgEY4BOAfABQCGddLAngFyJ04tiCADadEmANoBdADSIA5jiiE6Afl7hiOYGhzEAlL0wBYAFChIsBCjRZcBImURxqAKxzRmbDjz4ChYKLi0nKKyvS8TDCEyEb6iAC8DBRUtHSG4mYW0PBIqBhmiOL2hCTklDT0iAA+zm4eUHKFiABi4BAljuTY+KVOLu7QiKqIUTFxickVaYgaJNq6xGZe7Fy8-IIiYpKyCkoqvG2QiBnYAN7NEAikUHu3CXcqw49VkQBuvCxgnPFJiG-NfhQEB0JDUOAwYSsVacOSsOTUX7JJhhVjxdB3JiI54sWaIRH6MwAXzMZnyTAkAAY5ABGKTxAD0DOcAGsyWgKWd-ixhCAcLxKYgiXIuW8eXzeDShfTEEzEFBOAAHHC4dhwOjssCc7m8-mIABENP1QpFOolBtIpGNRJlcoVytVdHVmu1Yt1ArkLF4+pY1tNbvNNM93t90rkeEmiDwADoAzhGcy4GzTEA)

[I used this question on stackoverflow as a basis](https://stackoverflow.com/questions/65110771/how-to-have-functions-pass-arguments-with-the-same-overloads)

**Comment by rayepps** [comment]
Hey @MarlonPassos-git you are totally correct 🙏  I had mistyped those example, just updated them.

Thats so kool you got it to work! and so quickly!  I don't really mind the use of `function`. I _prefer_ const but this gives us a pretty big advantage with the types so I'd be willing to use it.

**Comment by MarlonPassos-git** [comment]
@rayepps  Alright, I'll open a PR for that.

 Regarding the use of const and function, do you have a specific reason for preferring const? Honestly, until today I haven't been able to find many differences besides the way it is written and how the function can be declared after its use. I don't even know if one is better than the other in some specific cases

**Comment by rayepps** [comment]
For me:

1. `const` enforces single assignment. Using function someone could reassign the function a new value. Dangerous.
2. `const` does not have its own lexical scope which means no `this` which I very much like to avoid.
3. `function` being hoisted, IMO, is a bug -- not a feature -- so I prefer to use `const` and structure my modules in a way that function hoisting isn't needed.

Everyone has their reasons but then again, it's really just preference :) There's nothing wrong with using `function`.
