### ISSUE TITLE
Lodash `merge` equivalent

### ISSUE THREAD

**Issue by apstanisic** [rayepps/radash#247]
I do not know if this is a bug or a feature request, depends on whether `assing` function is working as intended.

Lodash provides `merge` function, that is useful for merging multiple nested objects.
This library provides something similar with `assign`, but that function is replacing only values that already exists.

[runkit link](https://runkit.com/embed/w0yoasi22z7j)

```js
var radash = require("radash")
var lodash = require("lodash")

const left = { hello: "world", test: { me: "h" } }
const right = { hello: true, newP: "new property", test: { me: "new", v2: "added" } }
let raResult = radash.assign(left, right)
let loResult = lodash.merge(left, right)
// raResult does not have `newP` and `test.v2`
console.log({ loResult, raResult })
```

**Comment by rayepps** [comment]
Interesting, great find @apstanisic the docs and tests are a little ambiguous on this but, like you, I would expect it to include the new values from _right_. The fault here is actually mine because the unit tests don't cover this case and they should have from the start.

I can put a fix in for this unless you'de like to?

**Comment by apstanisic** [comment]
Sure, I'll create PR soon
