### ISSUE TITLE
Improve the omit function's performance

### ISSUE THREAD

**Issue by thegrumpysnail** [rayepps/radash#26]
Your omit function isn't performant. If you have an object with 20 keys, and you want to omit 5 of them, you have to create 15 objects in the process, not including the 5 objects you're creating when building the key map. I don't know TypeScript, so I don't plan on opening a PR, but you could do something like the following, which only results in the creation of one new object.

```js
export const omit = (
  obj,
  keys
) => {
  if (!obj) {
    return { };
  }

  if (!keys || keys.length === 0) {
    return obj;
  }

  const objCopy = { ...obj };

  keys.forEach((key) => {
    // Gross, I know, it's mutating the object, but it doesn't really matter
    // since you created the new object in this scope without modifying the
    // original object.
    delete objCopy[key];
  });

  return objCopy;
};
```

Also, your documentation for the [omit function](https://radash-docs.vercel.app/docs/object-omit) has a typo in it - `'source` <-- missing the closing single quote.

**Comment by rayepps** [comment]
It is so gross... haha but I understand the benefit. In my experience as a web engineer writing APIs on servers and apps on browsers, I have never once needed to optimize functions at this level for memory. On the other hand, I can't count the bugs born from using `delete`, `forEach`, and other data mutations. This is my ethos and why I've written Radash this way.

However, Radash is on some level now existing at the pleasure of the community so I'll leave this open for more comments. If I'm in the minority I'm open to changing it.

I'm curious, how important is a memory performance issue like this to you @thegrumpysnail ? Is it a non-starter or preference?

**Comment by thegrumpysnail** [comment]
Regarding the bugs with using delete, etc., I can definitely sympathize. But you have to consider the context in which you're working. You have a tiny function, and you're only doing the manipulation on an object that was immediately created within the same scope.

If you would prefer a more functional approach, you could do something like the following instead (I don't know if it would be any more performant, but worth throwing out there) -

```js
const omit = (
  obj,
  keys
) => {
  if (!obj) {
    return { };
  }

  if (!keys || keys.length === 0) {
    return obj;
  }

  const keySet = new Set(keys);

  const validEntries = Object.entries(obj)
    .filter(([ key ]) => !keySet.has(key));

  return Object.fromEntries(validEntries);
};
```

As far as memory performance issues go, it depends. For most frontend development and even most APIs, I doubt the object counts or sizes would be large enough for you to even notice. But in one application I maintained, excessive use of the spread operator did result in significant performance penalties when we were moving millions of large records between different systems. Beyond that, even if we added just 1 additional millisecond to each omit call, this would result in millions of milliseconds of extra overhead, which doesn't even count the extra work the GC is doing just to clean up the objects you didn't even need in the first place.

I vaguely recall the original implementation of lodash's omit function had performance issues. It might be worth considering putting together a benchmark test between radash and lodash as a selling point (assuming performance was on par or better).

**Comment by rayepps** [comment]
> you have to consider the context in which you're working. You have a tiny function, and you're only doing the manipulation on an object that was immediately created within the same scope
This is fair but also those bugs I faced drove me to a place mentally where I just totally reject code that could cause them. I'm still open to it thought, this is just why the current version is what it is.

> For most frontend development and even most APIs, I doubt the object counts or sizes would be large enough for you to even notice
Exactly! That's why I mentioned above my background to say that for me specifically (and I imagine everyone who does what I do on the web dev side) a performance _issue_ of this kind will never be known or seen. I see your point though, if you're an embedded engineer, doing IoT, or on the opposite side of the spectrum running ETL or big data pipelines ya you care a lot.

My ethos is, in my experience and on a general order of magnitude, companies don't suffer because their code isn't performant enough they suffer because their code isn't maintainable, understandable, and testable. When I work, I'm optimizing for those first and foremost. Companies that do suffer from performance typically only do so because they're getting traction and success (in the web dev world).

With all that said, I'm leaning hard towards rewriting it using the `delete` implementation. I'll probably add a comment about the special case. My ethos doesn't have to be a blind and deaf ideological mantra enforced on others :)  

There is still the matter of this comment (from medium)
> I would worry about the performance of the other functions based on the way this is written

I can tell you all the functions are written similarly. `omit` is probably the worst offender but my ethos will surely show throughout radash. I'm not sure if changing one means I should change them all to _performance first_ implementations.

**Comment by thegrumpysnail** [comment]
Oh yes, I completely understand why you did it the way you did. I've been there too, where functional pureness was the utmost priority. But that does have its limits much to my chagrin.

One thing worth noting is that you're now entering the world of building a general purpose library. That's a far cry from the usual application development that I suspect you're used to (but I could be wrong about that). In the application setting, you likely know the exact runtime characteristics of the code you're writing, while a library could be used anywhere and in any context.

> With all that said, I'm leaning hard towards rewriting it using the delete implementation. I'll probably add a comment about the special case. My ethos doesn't have to be a blind and deaf ideological mantra enforced on others :)

That's definitely a great quality! Some people tend to take things too far without being open to doing things in a slightly less pure way, so I'm happy to hear that you're entertaining the gross delete implementation. I agree that a comment would go a long way to explain the why.

Hmm. As far as changing all of them, I don't know if you have to necessarily go that far. At least not yet. `omit` is the one that caught my eye, so certainly a great one to start off with. Sometimes just being aware of these things is enough to help prevent future functions from falling into the same trap. Since you have your full suite of unit tests, at least you can be reasonably confident that any change you do make won't end up with a regression.

**Comment by rayepps** [comment]
> That's a far cry from the usual application development that I suspect you're used to 

Bullseye 🎯 ha that's why I'm fence sitting a lot of the issues being brought up. Knowing how to build an e-commerce platform and how to be the maintainer of a tiny (but apparently popular) repo is -- as I am now seeing -- not the same thing 😁 I'll get there.

I made the PR, couldn't bring myself to use the `forEach` 😆 but the result is the same.

**Comment by thegrumpysnail** [comment]
> I made the PR, couldn't bring myself to use the forEach laughing but the result is the same.

Lol, that's fair. I like your implementation too, so it's the best of both worlds. Thanks for addressing the concern above, and thank you for being open-minded!

**Comment by rayepps** [comment]
Version `v7.0.1` has been published with the performance improvement 🎉
