### ISSUE TITLE
Create `isEqual` function to check deep equality of Objects, Arrays and primitives 

### ISSUE THREAD

**Issue by touhidrahman** [rayepps/radash#28]

**Comment by rayepps** [comment]
Hey @touhidrahman, thanks for the issue. A few others brought this up to me personally, glad you made an issue. A few questions for ya:
1. Are you looking for feature parody with the Lodash `isEqual` function?
2. Given that this is typescript, I'm thinking about writing it to validate the types of the values are the same like `const isEqual = <TValue> (a: TValue, b: TValue)`. Is this how you would expect the types to work or would it be more helpful for them to be loose like `const isEqual = (a: any, b: any)`?

**Comment by touhidrahman** [comment]
Hi,

Yes, I would like it as a feature-parity of lodash's isEqual.

For my case, it should be sufficient to type as following :

isEqual(a: T1, b: T2): T1 is T2

However, the broader community should also put their opinions and then a agreeable solution be implemented.

Thanks for the hard work!

**Comment by iHazCode** [comment]
I could see value in having both with the default behavior for the isEqual feature potentially controlled with optional Boolean on the signature. While I could imagine the loose checker getting more mileage in the near-future, I might suggest the type checked version be the default since it seems to align more with the underlying theme of the library and would potentially become the more favorable option with time.

**Comment by rayepps** [comment]
If ya'll wanna check on my PR, specifically the test cases to make sure it covers any case you can think of that would be awesome!
