### ISSUE TITLE
Parallel signature question

### ISSUE THREAD

**Issue by rphlmr** [rayepps/radash#46]
Hi,

First, thanks for this lib ;)

Do you have a reason/use case to set `limit` as the first `parallel` function argument?

I don't pretend to know how everyone works but limiting parallel async calls is an exception in my use cases.

When I see `parallel` I guess it'll run all callback functions in parallel, based on the array.

I think of something like that : 
```ts
export const parallel = async <T, K>(
  array: T[],
  func: (item: T) => Promise<K>,
  limit: number = array.length,
): Promise<K[]>
```

Not dramatic, I still can do it like:
```ts
const users = await parallel(userIds.length, userIds, async (userId) => {
  return await api.users.find(userId)
})
```

It's like `map` signature in the end, but running all callbacks in parallel and not one after one.

**Comment by rayepps** [comment]
Hey @rphlmr thanks for the issue and the PR!

My team has a philosophy on this that I think might be one of those internal mantras the community as a whole (that radash now serves) won't agree with.

We intentionally put the `limit` at the start for readability. We replaced `lodash` with `radash` and then realized we could probably replace some other libs if we added one or two more functions. I wrote `parallel` specifically to replace [async-retry](https://www.npmjs.com/package/async-retry). One of the annoying things about async-retry for us was how it put the `config` object with the retry count as the last argument which made readability difficult in many cases. So, we put it as the first argument in `parallel`.

Our use case for `parallel` involves calling third part platforms, doing db writes, and pushing to a queue service. In all those cases we want to cap the concurrency. In production, we might need to make 1,000+ requests so if we don't cap the concurrency we could hurt our selves at that scale. So, we thought it best to require that first argument be a value to force engineers to set a reasonable value in each use case.

Thats the story/background. With all that said, I'm willing to make changes. Not all use cases are ours, I get that. I do think defaulting parallel to the length of the input array is questionable because you could use `Promise.all` and probably get a better experience. Maybe we could add an `all` function that implements a `Promise.all` equivalence that executes all the given functions at once but provides the improved error handling with an `AggregateError`.

**Comment by rphlmr** [comment]
Thanks for the story background, it makes sense 😉


I now understand why you made this choice and I have no problem with it.
Maybe do not lose your time with a new function as we can easily set the limit to the array size if we want.

After all It’s a good way to question ourselves when running a lot of promises at once 😅
